spring:
  application:
    name: flight-mvc-app
  # Port
  port: 8080
  # Docker compose
  docker:
    compose:
      enabled: true
      lifecycle-management: start_and_stop
      file: ./docker-compose-mvc.yml
  # maria db docker
  datasource:
    url: jdbc:mariadb://localhost:3307/flight?createDatabaseIfNotExist=true
    username: root
    password: dbpw
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
    #validate, none, update, create-drop
    hibernate:
      ddl-auto: validate
    # Debug queries
    show-sql: true
  test:
    database:
      replace: none
  # i18n configuration, without message source bean
  #messages:
  #  basename: message/message
  #  fallback-to-system-locale: true
  # Liquibase
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml
    contexts: development
    label-filter: development
    clear-checksums: false
    drop-first: false
  servlet:
    # Session
    session:
      timeout: 15m
      tracking-modes: COOKIE
    # Multipart
    multipart:
      max-file-size: 2MB
# Email
  mail:
    host: smtp.gmail.com
    port: 587
    username: andresruizpenuela@gmail.com
    password: ${EMAIL_PWD}
    properties:
      mail:
        debug: true
        transport:
          protocol: smtp
        smtp:
          port: 25
          auth: true
          starttls:
            enable: true
            required: true
# DEBUG LOGS
#logging:
#  level:
#    org:
#      h2: DEBUG
#    "liquibase": DEBUG
    #Para ver los parámetros de las querys
    #org.hibernate.SQL: DEBUG
    #org.hibernate.orm.jdbc.bind: TRACE

# Actuator:
# Activar endpoints predefinidos: management.endpoints.web.exposure.include= .....
# Desactivar un edpoint: management.endpoint.health.enable= false/true
management:
  endpoints:
    web:
      exposure:
        include: health, bean, info, auditevents, env, sessions, shutdown, metrics, prometheus, logfile, loggers, configprops, conditions
  endpoint:
    health:
      enabled: false
# define property, path where saved the resources
# store
# C:/Users/andre/eclipse-workspace/GitLab/TokioSpring/spring-boot-controller/flight-app-working-files
# NameClass.class.getLoader().getaPath() + ../flight-app-working-files
# Nota: si la ruta empiza por ../NameFolderOrFile o /../NameFolderOrFile,
# da el error: "The resource path has been normalized to [null]",
# para solventarlo debe empezar con /NameFolderOrFile or NomeFolderOrFile
# o cambiar el tipo de objeto a Stirng y luego crear el path
application:
  store:
    absolute-path: C:\\Users\\andre\\Documents\\SourceTree\\TokioSpringFlightRest\\resources
    relative-path: ..\\resources